import { DateTime } from 'luxon';

export const patients = [
  {
    patientDocument: 20000001,
    lastname: 'Cruz',
    name: 'Sofia',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('2000-01-01', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000002,
    lastname: 'López',
    name: 'Juan',
    gender: 'MALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1990-02-12', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000003,
    lastname: 'Fernandez',
    name: 'Ana',
    gender: 'FEMALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1988-03-21', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000004,
    lastname: 'Martinez',
    name: 'Carlos',
    gender: 'MALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1995-07-30', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000005,
    lastname: 'Gonzalez',
    name: 'Lucia',
    gender: 'FEMALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1993-09-18', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000006,
    lastname: 'Pérez',
    name: 'José',
    gender: 'MALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1994-04-13', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000007,
    lastname: 'Morales',
    name: 'Claudia',
    gender: 'FEMALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1997-11-08', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000008,
    lastname: 'Serrano',
    name: 'Miguel',
    gender: 'MALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1985-06-17', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000009,
    lastname: 'Ortiz',
    name: 'Manuela',
    gender: 'FEMALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1990-10-24', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000010,
    lastname: 'Vargas',
    name: 'Esteban',
    gender: 'MALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1999-12-30', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000011,
    lastname: 'Ramirez',
    name: 'Paula',
    gender: 'FEMALE',
    socialSecurity: 'Previsión Sanitaria',
    birthDate: DateTime.fromISO('1992-07-16', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000012,
    lastname: 'Mendoza',
    name: 'Gabriel',
    gender: 'MALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1986-02-27', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000013,
    lastname: 'Rojas',
    name: 'Santiago',
    gender: 'MALE',
    socialSecurity: 'Previsión Sanitaria',
    birthDate: DateTime.fromISO('2000-11-03', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000014,
    lastname: 'Castillo',
    name: 'María',
    gender: 'FEMALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1995-09-09', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000015,
    lastname: 'Sánchez',
    name: 'Francisco',
    gender: 'MALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1991-12-15', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000016,
    lastname: 'Gutierrez',
    name: 'Verónica',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1998-05-27', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000017,
    lastname: 'Silva',
    name: 'David',
    gender: 'MALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1997-01-20', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000018,
    lastname: 'Cabrera',
    name: 'Clara',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1994-11-22', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000019,
    lastname: 'Aguilar',
    name: 'Andrés',
    gender: 'MALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1990-06-05', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000020,
    lastname: 'Ruiz',
    name: 'Julieta',
    gender: 'FEMALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1999-09-28', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000021,
    lastname: 'Herrera',
    name: 'Sergio',
    gender: 'MALE',
    socialSecurity: 'Previsión Sanitaria',
    birthDate: DateTime.fromISO('1987-03-17', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000022,
    lastname: 'Ibarra',
    name: 'Martina',
    gender: 'FEMALE',
    socialSecurity: 'Medicus',
    birthDate: DateTime.fromISO('1993-07-10', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000023,
    lastname: 'Vega',
    name: 'Joaquín',
    gender: 'MALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1990-08-29', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000024,
    lastname: 'Soto',
    name: 'Teresa',
    gender: 'FEMALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1997-04-06', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000025,
    lastname: 'Paz',
    name: 'Rafael',
    gender: 'MALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1986-09-14', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000026,
    lastname: 'Campos',
    name: 'Valeria',
    gender: 'FEMALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1989-01-22', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000027,
    lastname: 'Villalobos',
    name: 'Hugo',
    gender: 'MALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1998-10-04', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000028,
    lastname: 'Bravo',
    name: 'Mariana',
    gender: 'FEMALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1987-11-25', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000029,
    lastname: 'Delgado',
    name: 'Víctor',
    gender: 'MALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1995-03-12', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000030,
    lastname: 'Escobar',
    name: 'Diana',
    gender: 'FEMALE',
    socialSecurity: 'Previsión Sanitaria',
    birthDate: DateTime.fromISO('1988-06-28', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000031,
    lastname: 'Torres',
    name: 'Emilio',
    gender: 'MALE',
    socialSecurity: 'Medicus',
    birthDate: DateTime.fromISO('1990-09-01', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000032,
    lastname: 'Ponce',
    name: 'Isabel',
    gender: 'FEMALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1994-02-11', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000033,
    lastname: 'Farías',
    name: 'Luis',
    gender: 'MALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1996-08-15', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000034,
    lastname: 'Navarro',
    name: 'Pilar',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1987-07-02', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000035,
    lastname: 'Valenzuela',
    name: 'Sebastiáan',
    gender: 'MALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1998-12-30', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000036,
    lastname: 'Montoya',
    name: 'Lorena',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1999-05-06', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000037,
    lastname: 'Salinas',
    name: 'Felipe',
    gender: 'MALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1993-02-14', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000038,
    lastname: 'Guerrero',
    name: 'Victoria',
    gender: 'FEMALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1995-08-18', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000039,
    lastname: 'Villareal',
    name: 'Tomás',
    gender: 'MALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1986-01-29', { zone: 'UTC' }),
  },
  // SIN TURNOS PREVIOS
  {
    patientDocument: 20000040,
    lastname: 'Flores',
    name: 'Raul',
    gender: 'MALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1996-10-08', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000041,
    lastname: 'Castro',
    name: 'Rosa',
    gender: 'FEMALE',
    socialSecurity: 'Previsión Sanitaria',
    birthDate: DateTime.fromISO('1995-01-14', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000042,
    lastname: 'Díaz',
    name: 'Enrique',
    gender: 'MALE',
    socialSecurity: 'Medicus',
    birthDate: DateTime.fromISO('1992-05-18', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000043,
    lastname: 'Ramos',
    name: 'Claudia',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1994-06-09', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000044,
    lastname: 'Romero',
    name: 'Alejandro',
    gender: 'MALE',
    socialSecurity: 'Sancor',
    birthDate: DateTime.fromISO('1989-12-11', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000045,
    lastname: 'Reyes',
    name: 'Elena',
    gender: 'FEMALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1991-03-20', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000046,
    lastname: 'León',
    name: 'Lorena',
    gender: 'FEMALE',
    socialSecurity: 'Medicare',
    birthDate: DateTime.fromISO('1991-11-19', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000047,
    lastname: 'Reynoso',
    name: 'Javier',
    gender: 'MALE',
    socialSecurity: 'Previsión Sanitaria',
    birthDate: DateTime.fromISO('1993-05-23', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000048,
    lastname: 'Correa',
    name: 'Bianca',
    gender: 'FEMALE',
    socialSecurity: 'Medicus',
    birthDate: DateTime.fromISO('1997-07-31', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000049,
    lastname: 'Vilchez',
    name: 'Pilar',
    gender: 'FEMALE',
    socialSecurity: 'Osde',
    birthDate: DateTime.fromISO('1996-08-28', { zone: 'UTC' }),
  },
  {
    patientDocument: 20000050,
    lastname: 'Romero',
    name: 'Claudio',
    gender: 'MALE',
    socialSecurity: 'PARTICULAR',
    birthDate: DateTime.fromISO('1993-06-08', { zone: 'UTC' }),
  },
];
